services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres_auth
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - MIGRATION_PATH=${MIGRATION_PATH}
      - URI=${URI}
      - URL=${URL}
    depends_on:
      - postgres_auth
    command: ["auth"]
    restart: always

  postgres_auth:
    image: postgres:15-alpine
    container_name: postgres_auth
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth:/var/lib/postgresql/data

volumes:
  postgres_auth: